name: CI

on:

  workflow_dispatch: # Sirve para ejecutar la pipeline mediante un boton en GitHUb Actions
    
  pull_request:
    branches: [ main ]
    paths: ['hangman-api/**']


  # audit:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: inspect
  #       run: |
  #         ls -al
  #         whoami
  #         pwd
  #         node -v
jobs:

  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: build
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: hangman-api/node_modules/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - uses: actions/checkout@v3
     - uses: actions/download-artifact@v3
       with:
        name: dependencies
        path: hangman-api/node_modules/
     - name: test
       working-directory: ./hangman-api
       run: |
        npm test
        

