name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - "hangman-api/**"
  pull_request:
    branches: [ main ]
    paths: ['hangman-api/**']


  # audit:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: inspect
  #       run: |
  #         ls -al
  #         whoami
  #         pwd
  #         node -v
jobs:

  build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: build
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        working-directory: ./hangman-api
        run: |
          npm ci
          npm test
