name: Ejercicio2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: hangman-front/package-lock.json
      - name: build
        working-directory: ./hangman-front
        run: |
          npm ci
          npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
          name: build-code
          path: hangman-front/dist/
  
  delivery:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build

    steps: 
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-code
          path: hangman-front/dist/
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build Docker And Push
        with:
          image: hangman-front
          tags: $(date +%s), latest
          registry: ghcr.io
          directory: "./hangman-front"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      


